import type { IntelligenceAgentDefinition, IntelligenceAgentId } from "./types";

export const INTELLIGENCE_AGENTS: IntelligenceAgentDefinition[] = [
  {
    id: "oyi",
    name: "Oyi Intelligence",
    domain: "resident home and estate operations",
    allowed_surfaces: ["consumer", "watch", "api"],
    tools: ["oyi:*"],
    memory_scope: ["user", "home", "estate"],
    risk_level: "medium",
    default_response_tone: "calm resident-facing home assistant",
  },
  {
    id: "facility",
    name: "Facility Intelligence",
    domain: "estate and facility operations",
    allowed_surfaces: ["facility", "api"],
    tools: ["oyi:read", "facility:*", "camera:read"],
    memory_scope: ["facility", "estate", "system"],
    risk_level: "high",
    default_response_tone: "operational, concise, permission-aware",
  },
  {
    id: "oma",
    name: "Ochiga Marketing Agent",
    domain: "marketing qualification and lead capture",
    allowed_surfaces: ["office", "website", "widget", "whatsapp", "api"],
    tools: ["office:create_lead", "office:get_solution_fit", "office:notify_founder"],
    memory_scope: ["office", "lead"],
    risk_level: "medium",
    default_response_tone: "commercial, helpful, non-overclaiming",
  },
  {
    id: "osa",
    name: "Ochiga Sales Agent",
    domain: "sales follow-up, demos, proposals, and handoff",
    allowed_surfaces: ["office", "website", "widget", "whatsapp", "api"],
    tools: ["office:update_lead_status", "office:schedule_demo", "office:notify_founder"],
    memory_scope: ["office", "lead"],
    risk_level: "medium",
    default_response_tone: "commercial, precise, conversion-aware",
  },
  {
    id: "edge",
    name: "Edge Intelligence",
    domain: "local runtime, physical devices, and camera edge health",
    allowed_surfaces: ["edge", "api"],
    tools: ["edge:health", "edge:camera_registry", "edge:stream_health"],
    memory_scope: ["edge", "camera", "system"],
    risk_level: "high",
    default_response_tone: "diagnostic, safe, local-runtime aware",
  },
  {
    id: "camera",
    name: "Camera Intelligence",
    domain: "camera events, stream health, and future detections",
    allowed_surfaces: ["facility", "camera", "edge", "api"],
    tools: ["camera:read", "camera:event_ingest", "camera:profile"],
    memory_scope: ["camera", "estate", "facility"],
    risk_level: "high",
    default_response_tone: "security-aware, factual, no fabricated detections",
  },
  {
    id: "watch",
    name: "Watch Intelligence",
    domain: "wrist awareness, quick actions, and home status",
    allowed_surfaces: ["watch", "consumer", "api"],
    tools: ["watch:summary", "watch:quick_actions", "oyi:scene"],
    memory_scope: ["user", "home"],
    risk_level: "medium",
    default_response_tone: "glanceable, compact, resident-safe",
  },
  {
    id: "twin",
    name: "Digital Twin Intelligence",
    domain: "future digital twin understanding",
    allowed_surfaces: ["facility", "office", "api"],
    tools: [],
    memory_scope: ["estate", "facility", "system"],
    risk_level: "high",
    default_response_tone: "spatial, operational, evidence-based",
  },
  {
    id: "plan_studio",
    name: "Plan Studio Intelligence",
    domain: "future planning and design workflows",
    allowed_surfaces: ["office", "api"],
    tools: [],
    memory_scope: ["office", "system"],
    risk_level: "medium",
    default_response_tone: "planning-focused and structured",
  },
];

export function getIntelligenceAgent(id: IntelligenceAgentId) {
  return INTELLIGENCE_AGENTS.find((agent) => agent.id === id) || null;
}
