import { Request,Response } from "express";
import { queryDetections } from "../modules/cameras/cameraDetection.service";
import { supabaseAdmin } from "../supabase/supabaseClient";
import { canAccessCamera } from "../modules/cameras/cameraAccess.policy";
import { normalizeDetectionType } from "../modules/cameras/cameraDetection.types";
export async function listCameraDetections(req:Request,res:Response){const result=await queryDetections({cameraId:req.params.cameraId,user:(req as any).user,query:req.query});if(!result.ok)return res.status(result.code==="detection_access_denied"?403:400).json({error:result.code});return res.json(result)}
export async function listEventDetections(req:Request,res:Response){const result=await queryDetections({eventId:req.params.eventId,user:(req as any).user,query:req.query});if(!result.ok)return res.status(result.code==="detection_access_denied"?403:400).json({error:result.code});return res.json(result)}
async function cameraForUser(cameraId:string,user:any){const {data}=await supabaseAdmin.from("facility_cameras").select("id,estate_id,metadata").eq("id",cameraId).maybeSingle();return data&&canAccessCamera(data,user).ok?data:null}
export async function listDetectionZones(req:Request,res:Response){const camera=await cameraForUser(req.params.cameraId,(req as any).user);if(!camera)return res.status(403).json({error:"detection_access_denied"});const {data,error}=await supabaseAdmin.from("camera_detection_zones").select("id,camera_id,name,kind,geometry,enabled,detection_types,minimum_confidence,restricted").eq("camera_id",camera.id).order("name");if(error)return res.status(500).json({error:"detection_zone_query_failed"});return res.json({items:data||[]})}
export async function upsertDetectionZone(req:Request,res:Response){const camera=await cameraForUser(req.params.cameraId,(req as any).user);if(!camera)return res.status(403).json({error:"detection_access_denied"});const geometry=Array.isArray(req.body?.geometry)?req.body.geometry.slice(0,32).map((p:any)=>({x:Number(p?.x),y:Number(p?.y)})):[];const kind=req.body?.kind==="line"?"line":"region";const required=kind==="line"?2:3;if(geometry.length<required||geometry.some((p:any)=>!Number.isFinite(p.x)||!Number.isFinite(p.y)||p.x<0||p.x>1||p.y<0||p.y>1))return res.status(400).json({error:"invalid_detection_zone_geometry"});const name=String(req.body?.name||"").trim().slice(0,100);if(!name)return res.status(400).json({error:"invalid_detection_zone_name"});const minimum=req.body?.minimumConfidence==null?null:Number(req.body.minimumConfidence);if(minimum!==null&&(!Number.isFinite(minimum)||minimum<0||minimum>1))return res.status(400).json({error:"invalid_detection_confidence"});const row={camera_id:camera.id,estate_id:camera.estate_id,home_id:camera.metadata?.home_id||null,name,kind,geometry,enabled:req.body?.enabled!==false,detection_types:Array.isArray(req.body?.detectionTypes)?req.body.detectionTypes.slice(0,20).map(normalizeDetectionType):[],minimum_confidence:minimum,restricted:req.body?.restricted===true,updated_at:new Date().toISOString()};const {data,error}=await supabaseAdmin.from("camera_detection_zones").upsert(row as any,{onConflict:"camera_id,name"}).select("*").single();if(error)return res.status(500).json({error:"detection_zone_persistence_failed"});return res.status(201).json(data)}
