import { Request,Response } from "express";
import { supabaseAdmin } from "../supabase/supabaseClient";
import { canAccessCamera } from "../modules/cameras/cameraAccess.policy";
import { mediaReference,signedMediaAccess } from "../modules/cameras/cameraMedia.service";
import { emitAuditEvent } from "../core/foundation";
import { randomUUID } from "crypto";

const clamp=(v:any,f=50)=>Math.min(100,Math.max(1,Number.isFinite(Number(v))?Number(v):f));
const encodeCursor=(row:any)=>Buffer.from(JSON.stringify({at:row.captured_at,id:row.id})).toString("base64url");
const decodeCursor=(value:any)=>{try{const parsed=JSON.parse(Buffer.from(String(value),"base64url").toString("utf8"));return Number.isFinite(Date.parse(parsed?.at))&&/^[0-9a-f-]{36}$/i.test(String(parsed?.id||""))?parsed:null;}catch{return null;}};
async function cameraAccess(cameraId:string,user:any){const {data:camera}=await supabaseAdmin.from("facility_cameras").select("id,estate_id,name,edge_node_id,metadata").eq("id",cameraId).maybeSingle();if(!camera)return{ok:false as const,status:404,code:"media_not_found"};const access=canAccessCamera(camera,user);return access.ok?{ok:true as const,camera}:{ok:false as const,status:403,code:"media_access_denied"};}
export async function requestSnapshot(req:Request,res:Response){const user=req.user as any;const access=await cameraAccess(req.params.cameraId,user);if(!access.ok)return res.status(access.status).json({error:access.code});if(!access.camera.edge_node_id)return res.status(409).json({error:"snapshot_unavailable"});const id=randomUUID(),now=Date.now();const payload={requestId:id,cameraId:access.camera.id,eventId:req.body?.eventId||null,kind:req.body?.eventId?"event_snapshot":"snapshot",retention:req.body?.eventId?"security":"standard",timeoutMs:8000};const {data,error}=await supabaseAdmin.from("edge_commands").insert({id,estate_id:access.camera.estate_id,home_id:access.camera.metadata?.home_id||null,edge_node_id:access.camera.edge_node_id,command_type:"camera.snapshot",status:"pending",payload,requested_by:user.id,requested_surface:access.camera.metadata?.privacy_scope==="home"?"consumer":"facility",expires_at:new Date(now+120000).toISOString()} as any).select("id,status,expires_at").single();if(error)return res.status(503).json({error:"snapshot_unavailable"});return res.status(202).json({ok:true,command:{id:data.id,status:data.status,expiresAt:data.expires_at}});}
export async function listCameraMedia(req:Request,res:Response){const user=req.user as any;const access=await cameraAccess(req.params.cameraId,user);if(!access.ok)return res.status(access.status).json({error:access.code});const limit=clamp(req.query.limit);let query=supabaseAdmin.from("camera_media").select("*").eq("camera_id",access.camera.id).neq("status","deleted").order("captured_at",{ascending:false}).order("id",{ascending:false}).limit(limit+1);if(req.query.kind)query=query.eq("kind",String(req.query.kind));if(req.query.start)query=query.gte("captured_at",String(req.query.start));if(req.query.end)query=query.lte("captured_at",String(req.query.end));if(req.query.cursor){const cursor=decodeCursor(req.query.cursor);if(!cursor)return res.status(400).json({error:"invalid_cursor"});query=query.or(`captured_at.lt.${cursor.at},and(captured_at.eq.${cursor.at},id.lt.${cursor.id})`);}if(req.query.eventId){const {data:links}=await supabaseAdmin.from("camera_event_media").select("media_id").eq("event_id",String(req.query.eventId));query=query.in("id",(links||[]).map((x:any)=>x.media_id));}const {data,error}=await query;if(error)return res.status(500).json({error:"storage_unavailable"});const rows=data||[],hasMore=rows.length>limit,items=rows.slice(0,limit);return res.json({ok:true,items:items.map(mediaReference),nextCursor:hasMore&&items.length?encodeCursor(items[items.length-1]):null});}
export async function listEventMedia(req:Request,res:Response){const user=req.user as any;const {data:event}=await supabaseAdmin.from("camera_events").select("id,camera_id").eq("id",req.params.eventId).maybeSingle();if(!event)return res.status(404).json({error:"media_not_found"});const access=await cameraAccess(event.camera_id,user);if(!access.ok)return res.status(access.status).json({error:access.code});const {data:links}=await supabaseAdmin.from("camera_event_media").select("relationship,camera_media(*)").eq("event_id",event.id);return res.json({ok:true,items:(links||[]).map((row:any)=>({...mediaReference(row.camera_media),relationship:row.relationship}))});}
export async function createMediaAccess(req:Request,res:Response){const user=req.user as any;const result=await signedMediaAccess(req.params.mediaId,user);void emitAuditEvent({actorId:user?.id,actorEmail:user?.email,actorRole:user?.role,action:"camera.media.accessed",resourceType:"camera_media",resourceId:req.params.mediaId,estateId:result.ok?(result.camera as any)?.estate_id:undefined,status:result.ok?"success":"denied",metadata:{code:result.ok?"issued":result.code},req} as any);if(!result.ok)return res.status(result.code==="media_not_found"?404:result.code==="media_expired"?410:403).json({error:result.code});return res.json({ok:true,media:result.media,accessUrl:result.accessUrl,accessExpiresAt:result.accessExpiresAt});}
export async function preserveMedia(req:Request,res:Response){const user=req.user as any;const {data:media}=await supabaseAdmin.from("camera_media").select("id,camera_id,status,preserved_at").eq("id",req.params.mediaId).maybeSingle();if(!media)return res.status(404).json({error:"media_not_found"});const access=await cameraAccess(media.camera_id,user);if(!access.ok)return res.status(access.status).json({error:access.code});if(media.status!=="ready")return res.status(409).json({error:"media_expired"});const now=new Date().toISOString();const {data,error}=await supabaseAdmin.from("camera_media").update({retention_class:"evidence",expires_at:null,preserved_at:media.preserved_at||now,preserved_by:user.id,preservation_reason:String(req.body?.reason||"Security evidence").slice(0,500),updated_at:now}).eq("id",media.id).eq("status","ready").select("*").maybeSingle();if(error)return res.status(500).json({error:"storage_unavailable"});if(!data)return res.status(409).json({error:"retention_locked"});return res.json({ok:true,media:mediaReference(data)});}
export async function getRecordingPolicy(req:Request,res:Response){const user=req.user as any;const access=await cameraAccess(req.params.cameraId,user);if(!access.ok)return res.status(access.status).json({error:access.code});const {data}=await supabaseAdmin.from("camera_recording_policies").select("camera_id,mode,event_pre_roll_seconds,event_post_roll_seconds,retention_days,schedule,provider,updated_at").eq("camera_id",access.camera.id).maybeSingle();return res.json({ok:true,policy:data||{camera_id:access.camera.id,mode:"off"}});}
export async function putRecordingPolicy(req:Request,res:Response){const user=req.user as any;const access=await cameraAccess(req.params.cameraId,user);if(!access.ok)return res.status(access.status).json({error:access.code});const mode=String(req.body?.mode||"off");if(!["off","event_only","continuous","scheduled"].includes(mode))return res.status(400).json({error:"recording_unavailable"});const row={camera_id:access.camera.id,estate_id:access.camera.estate_id,mode,event_pre_roll_seconds:req.body?.eventPreRollSeconds??null,event_post_roll_seconds:req.body?.eventPostRollSeconds??null,retention_days:req.body?.retentionDays??null,schedule:req.body?.schedule||null,provider:req.body?.provider||null,updated_by:user.id,updated_at:new Date().toISOString()};const {data,error}=await supabaseAdmin.from("camera_recording_policies").upsert(row as any).select("*").single();if(error)return res.status(400).json({error:"recording_unavailable"});return res.json({ok:true,policy:data});}
