import crypto from "crypto";
import { supabaseAdmin } from "../../supabase/supabaseClient";
import { canAccessCamera } from "./cameraAccess.policy";
import { CameraMediaStore, SupabaseCameraMediaStore } from "./cameraMedia.store";
import { CAMERA_MEDIA_KINDS, CameraMediaKind, CameraMediaRetention, MEDIA_ACCESS_TTL_SECONDS, verifyMediaContent } from "./cameraMedia.types";
import { operationalMetrics } from "../../observability/metrics";
import { emitAuditEvent } from "../../core/foundation";

const bucket=process.env.CAMERA_MEDIA_BUCKET||"camera-media-private";
const text=(v:any)=>String(v??"").trim();
const cameraSelect="id,estate_id,edge_node_id,name,metadata";
const retentionDays:Record<CameraMediaRetention,number|null>={ephemeral:1,standard:30,security:90,evidence:null};
const safeMetadata=(value:any)=>value&&typeof value==="object"&&!Array.isArray(value)?Object.fromEntries(Object.entries(value).filter(([key])=>!["url","path","storage_key","password","token","secret"].includes(key.toLowerCase()))):{};
export const mediaReference=(row:any)=>({id:row.id,cameraId:row.camera_id,eventId:row.event_id||null,kind:row.kind,capturedAt:row.captured_at,durationMs:row.duration_ms??null,mimeType:row.mime_type??null,sizeBytes:row.size_bytes??null,status:row.status,retention:row.retention_class,expiresAt:row.expires_at??null,preservedAt:row.preserved_at??null,source:row.source,available:row.status==="ready"&&(!row.expires_at||Date.parse(row.expires_at)>Date.now())});

export async function resolveCameraForEdge(cameraId:string,siteId:string,nodeId:string){const {data}=await supabaseAdmin.from("facility_cameras").select(cameraSelect).eq("id",cameraId).eq("estate_id",siteId).eq("edge_node_id",nodeId).maybeSingle();return data;}
export async function resolveMediaAccess(mediaId:string,user:any){const {data:media}=await supabaseAdmin.from("camera_media").select("*").eq("id",mediaId).maybeSingle();if(!media)return{ok:false as const,code:"media_not_found"};const {data:camera}=await supabaseAdmin.from("facility_cameras").select(cameraSelect).eq("id",media.camera_id).maybeSingle();const access=canAccessCamera(camera,user);if(!access.ok)return{ok:false as const,code:"media_access_denied"};if(media.status!=="ready"||media.expires_at&&Date.parse(media.expires_at)<=Date.now())return{ok:false as const,code:"media_expired"};return{ok:true as const,media,camera};}

export async function ingestEdgeMedia(input:{cameraId:string;siteId:string;nodeId:string;kind:string;mimeType:string;base64:string;capturedAt?:string;durationMs?:number;eventId?:string;idempotencyKey:string;retention?:CameraMediaRetention;metadata?:any},store:CameraMediaStore=new SupabaseCameraMediaStore()){
  if(!CAMERA_MEDIA_KINDS.includes(input.kind as any))return{ok:false as const,code:"unsupported_media_kind"};
  const camera=await resolveCameraForEdge(input.cameraId,input.siteId,input.nodeId);if(!camera)return{ok:false as const,code:"media_access_denied"};
  const keyToken=text(input.idempotencyKey).slice(0,160);if(!keyToken)return{ok:false as const,code:"media_upload_failed"};
  const {data:existing}=await supabaseAdmin.from("camera_media").select("*").eq("camera_id",camera.id).eq("idempotency_key",keyToken).maybeSingle();if(existing)return{ok:true as const,created:false,media:existing,reference:mediaReference(existing)};
  let bytes:Buffer;try{bytes=Buffer.from(input.base64,"base64");}catch{return{ok:false as const,code:"media_upload_failed"};}
  const verified=verifyMediaContent(bytes,input.mimeType,input.kind as CameraMediaKind);if(!verified.ok)return verified;
  const capturedAt=text(input.capturedAt)&&Number.isFinite(Date.parse(input.capturedAt!))?input.capturedAt!:new Date().toISOString();const retention=input.retention&&retentionDays[input.retention]!==undefined?input.retention:(input.kind==="event_snapshot"?"security":"standard");const days=retentionDays[retention];const expiresAt=days?new Date(Date.parse(capturedAt)+days*86400000).toISOString():null;const id=crypto.randomUUID();const ext=input.mimeType==="image/jpeg"?"jpg":input.mimeType==="image/webp"?"webp":"mp4";const storageKey=`${camera.estate_id}/${camera.id}/${capturedAt.slice(0,10)}/${id}.${ext}`;const sha=crypto.createHash("sha256").update(bytes).digest("hex");
  await store.put(storageKey,bytes,input.mimeType);
  const row={id,camera_id:camera.id,estate_id:camera.estate_id,home_id:camera.metadata?.home_id||null,kind:input.kind,captured_at:capturedAt,duration_ms:input.durationMs??null,mime_type:input.mimeType,size_bytes:bytes.length,content_sha256:sha,storage_provider:"supabase",storage_bucket:bucket,storage_key:storageKey,status:"ready",retention_class:retention,expires_at:expiresAt,source:"edge",edge_node_id:input.nodeId,idempotency_key:keyToken,metadata:safeMetadata(input.metadata)};
  const {data:media,error}=await supabaseAdmin.from("camera_media").insert(row as any).select("*").single();if(error){await store.delete(storageKey).catch(()=>{});const {data:retry}=await supabaseAdmin.from("camera_media").select("*").eq("camera_id",camera.id).eq("idempotency_key",keyToken).maybeSingle();if(retry)return{ok:true as const,created:false,media:retry,reference:mediaReference(retry)};return{ok:false as const,code:"media_upload_failed"};}
  if(input.eventId){const {data:event}=await supabaseAdmin.from("camera_events").select("id,camera_id,estate_id,metadata").eq("id",input.eventId).eq("camera_id",camera.id).eq("estate_id",camera.estate_id).maybeSingle();if(!event){await store.delete(storageKey).catch(()=>{});await supabaseAdmin.from("camera_media").delete().eq("id",id);return{ok:false as const,code:"media_access_denied"};}await supabaseAdmin.from("camera_event_media").upsert({event_id:event.id,media_id:id,relationship:input.kind==="clip"?"clip":"evidence"} as any);const evidence=Array.isArray(event.metadata?.media_evidence)?event.metadata.media_evidence:[];await supabaseAdmin.from("camera_events").update({metadata:{...safeMetadata(event.metadata),media_evidence:[...evidence.filter((item:any)=>item?.media_id!==id),{media_id:id,kind:input.kind,captured_at:capturedAt,authorized_available:true}].slice(-10)}} as any).eq("id",event.id).eq("camera_id",camera.id);}
  await supabaseAdmin.from("facility_cameras").update({last_seen_at:capturedAt,metadata:{...camera.metadata,frame_freshness_at:capturedAt},updated_at:new Date().toISOString()} as any).eq("id",camera.id).eq("estate_id",camera.estate_id).eq("edge_node_id",input.nodeId);
  operationalMetrics.increment("camera_media_upload_total",{kind:input.kind});operationalMetrics.observe("camera_media_upload_bytes",bytes.length,{kind:input.kind});return{ok:true as const,created:true,media,reference:mediaReference(media)};
}

export async function signedMediaAccess(mediaId:string,user:any,store:CameraMediaStore=new SupabaseCameraMediaStore()){const access=await resolveMediaAccess(mediaId,user);if(!access.ok)return access;if(!await store.exists(access.media.storage_key))return{ok:false as const,code:"media_not_found"};const signed=await store.getSignedRead(access.media.storage_key,MEDIA_ACCESS_TTL_SECONDS);operationalMetrics.increment("camera_media_access_total",{kind:access.media.kind});return{ok:true as const,media:mediaReference(access.media),accessUrl:signed.url,accessExpiresAt:signed.expiresAt,camera:access.camera};}

export async function cleanupExpiredMedia(store:CameraMediaStore=new SupabaseCameraMediaStore(),now=new Date().toISOString(),limit=100){const {data}=await supabaseAdmin.from("camera_media").select("*").eq("status","ready").is("preserved_at",null).neq("retention_class","evidence").lte("expires_at",now).limit(Math.min(500,Math.max(1,limit)));let deleted=0;for(const row of data||[]){const {data:claimed}=await supabaseAdmin.from("camera_media").update({status:"expired",updated_at:now} as any).eq("id",row.id).eq("status","ready").is("preserved_at",null).neq("retention_class","evidence").select("id").maybeSingle();if(!claimed)continue;try{await store.delete(row.storage_key);await supabaseAdmin.from("camera_media").update({status:"deleted",updated_at:now,metadata:{...safeMetadata(row.metadata),deleted_by:"retention_worker",deleted_at:now}} as any).eq("id",row.id).eq("status","expired");deleted++;void emitAuditEvent({actorId:"camera_media_retention_worker",actorEmail:"system@oyi.local",actorRole:"system",action:"camera.media.retention_deleted",resourceType:"camera_media",resourceId:row.id,estateId:row.estate_id,status:"success",metadata:{kind:row.kind,retention_class:row.retention_class}} as any);}catch{await supabaseAdmin.from("camera_media").update({status:"ready",updated_at:now} as any).eq("id",row.id).eq("status","expired");}}operationalMetrics.increment("camera_media_retention_deleted_total",{},deleted);return{examined:(data||[]).length,deleted};}
