import crypto from "crypto";
import { supabaseAdmin } from "../../supabase/supabaseClient";
import { canAccessCamera } from "./cameraAccess.policy";
import { normalizeBoundingBox, normalizeDetectionType } from "./cameraDetection.types";
import { normalizeIntelligenceEvent, publishIntelligenceEvent } from "../../intelligence-core";
import { NotificationService } from "../../services/NotificationService";

const text=(v:any)=>String(v??"").trim();
export function safeDetectionAttributes(raw:any){const out:Record<string,string|number|boolean|null>={};if(!raw||typeof raw!=="object"||Array.isArray(raw))return out;for(const [key,value] of Object.entries(raw).slice(0,24)){if(!/^[A-Za-z][A-Za-z0-9_]{0,47}$/.test(key)||/(url|token|secret|password|credential|image|tensor|embedding)/i.test(key))continue;if(value===null||typeof value==="boolean"||typeof value==="number"&&Number.isFinite(value)||typeof value==="string"&&value.length<=160)out[key]=value as any}return out}
export function aggregationKey(input:{cameraId:string;type:string;zoneId?:string|null;trackingId?:string|null;observedAt:string},windowSeconds=15){const bucket=Math.floor(Date.parse(input.observedAt)/(Math.max(5,windowSeconds)*1000));return[input.cameraId,input.type,input.zoneId||"-",input.trackingId||"-",bucket].join(":")}
export function detectionSeverity(input:{type:string;restricted?:boolean;observedAt:string;confidence?:number|null}){const hour=new Date(input.observedAt).getUTCHours();if(input.type==="fire"||input.type==="smoke")return"critical";if(input.restricted&&(hour<6||hour>=22))return"high";if(input.type==="zone_intrusion"||input.type==="tamper")return"high";if((input.confidence||0)>=.85&&(input.type==="person"||input.type==="vehicle"))return"medium";return"info"}
export function conciseDetectionEvidence(rows:any[]){const counts=new Map<string,number>();for(const row of rows)counts.set(row.detection_type,(counts.get(row.detection_type)||0)+1);return{detections:[...counts].map(([type,count])=>({type,count})),zones:[...new Set(rows.map(r=>r.zone_name).filter(Boolean))].slice(0,5),media_available:rows.some(r=>r.media_id),observed_at:rows.map(r=>r.observed_at).sort().at(-1)||null,identity_claims:false}}
export async function ingestEdgeDetections(input:{cameraId:string;siteId:string;nodeId:string;provider:string;model?:string;modelVersion?:string;detections:any[];mediaId?:string}){
 const {data:camera}=await supabaseAdmin.from("facility_cameras").select("id,estate_id,edge_node_id,name,metadata").eq("id",input.cameraId).eq("estate_id",input.siteId).eq("edge_node_id",input.nodeId).maybeSingle();if(!camera)return{ok:false as const,code:"detection_access_denied"};
 if(!text(input.provider)||!Array.isArray(input.detections)||input.detections.length<1||input.detections.length>50)return{ok:false as const,code:"invalid_detection_payload"};
 let media:any=null;if(input.mediaId){const result=await supabaseAdmin.from("camera_media").select("id,camera_id,estate_id").eq("id",input.mediaId).eq("camera_id",camera.id).eq("estate_id",camera.estate_id).maybeSingle();media=result.data;if(!media)return{ok:false as const,code:"invalid_media_relationship"}}
 const persisted:any[]=[];let event:any=null;
 for(const raw of input.detections){const observedAt=text(raw.observed_at||raw.observedAt);if(!observedAt||!Number.isFinite(Date.parse(observedAt))||Math.abs(Date.now()-Date.parse(observedAt))>7*86400000)return{ok:false as const,code:"invalid_detection_timestamp"};const confidence=raw.confidence==null?null:Number(raw.confidence);if(confidence!==null&&(!Number.isFinite(confidence)||confidence<0||confidence>1))return{ok:false as const,code:"invalid_detection_confidence"};const requestedBox=raw.bounding_box??raw.boundingBox??raw.bbox;const box=requestedBox==null?null:normalizeBoundingBox(requestedBox);if(requestedBox!=null&&!box)return{ok:false as const,code:"invalid_detection_bounding_box"};const type=normalizeDetectionType(raw.type||raw.label);const zoneId=text(raw.zone_id||raw.zoneId)||null;let zone:any=null;if(zoneId){const z=await supabaseAdmin.from("camera_detection_zones").select("id,name,restricted,minimum_confidence").eq("id",zoneId).eq("camera_id",camera.id).eq("estate_id",camera.estate_id).maybeSingle();zone=z.data;if(!zone)return{ok:false as const,code:"invalid_detection_zone"};if(zone.minimum_confidence!=null&&confidence!=null&&confidence<zone.minimum_confidence)continue}
  const key=aggregationKey({cameraId:camera.id,type,zoneId,trackingId:text(raw.tracking_id||raw.trackingId)||null,observedAt});const idempotency=text(raw.idempotency_key||raw.provider_observation_id)||crypto.createHash("sha256").update(`${key}:${observedAt}`).digest("hex");const {data:existing}=await supabaseAdmin.from("camera_detections").select("*").eq("camera_id",camera.id).eq("idempotency_key",idempotency).maybeSingle();if(existing){persisted.push(existing);event=event||existing.event_id&&{id:existing.event_id};continue}
  if(!event){const since=new Date(Date.parse(observedAt)-15000).toISOString();const recent=await supabaseAdmin.from("camera_events").select("*").eq("camera_id",camera.id).eq("event_type","activity_detected").gte("created_at",since).contains("metadata",{aggregation_key:key}).order("created_at",{ascending:false}).limit(1).maybeSingle();event=recent.data;if(!event){const severity=detectionSeverity({type,restricted:zone?.restricted,observedAt,confidence});const core=normalizeIntelligenceEvent({agent_id:"camera",surface:"edge",actor_id:input.nodeId,estate_id:camera.estate_id,camera_id:camera.id,event_type:"activity_detected",category:"Camera",title:`Activity detected on ${camera.name||"camera"}`,summary:`${type.replace(/_/g," ")} detected${zone?.name?` in ${zone.name}`:""}.`,confidence:confidence!==null&&confidence>=.8?"confirmed":"probable",source:"edge_camera_detection",metadata:{aggregation_key:key,severity,zone:zone?.name||null},occurred_at:observedAt});const inserted=await supabaseAdmin.from("camera_events").insert({camera_id:camera.id,estate_id:camera.estate_id,event_type:"activity_detected",confidence,message:core.summary,source_timestamp:observedAt,metadata:{source:"edge_camera_detection",edge_node_id:input.nodeId,aggregation_key:key,severity,detection_summary:{[type]:1},zone_id:zoneId,zone_name:zone?.name||null,media_evidence:media?[{media_id:media.id,kind:"event_snapshot",authorized_available:true}]:[]}} as any).select("*").single();if(inserted.error)return{ok:false as const,code:"detection_event_failed"};event=inserted.data;if(media)await supabaseAdmin.from("camera_event_media").upsert({event_id:event.id,media_id:media.id,relationship:"evidence"} as any);await publishIntelligenceEvent(core,{source_table:"camera_events",source_event_id:event.id});if(["high","critical"].includes(severity))void NotificationService.sendToEstate(camera.estate_id,{type:"security",title:core.title,message:core.summary,payload:{camera_event_id:event.id,camera_id:camera.id,camera_media_id:media?.id||null,severity,source:"camera_detection_runtime"},entityId:event.id}).catch(()=>{})}}
  const expiresAt=new Date(Date.parse(observedAt)+(event?.id?90:7)*86400000).toISOString();const inserted=await supabaseAdmin.from("camera_detections").insert({camera_id:camera.id,estate_id:camera.estate_id,home_id:camera.metadata?.home_id||null,event_id:event?.id||null,media_id:media?.id||null,detection_type:type,observed_at:observedAt,confidence,bounding_box:box,visual_zone_id:zoneId,tracking_id:text(raw.tracking_id||raw.trackingId).slice(0,128)||null,attributes:safeDetectionAttributes(raw.attributes),provider:text(input.provider).slice(0,80),model:text(input.model).slice(0,80)||null,model_version:text(input.modelVersion).slice(0,80)||null,provider_observation_id:text(raw.provider_observation_id).slice(0,160)||null,idempotency_key:idempotency.slice(0,200),aggregation_key:key,expires_at:expiresAt} as any).select("*").single();if(inserted.error)return{ok:false as const,code:"detection_persistence_failed"};persisted.push(inserted.data)}
 return{ok:true as const,event,detections:persisted,evidence:conciseDetectionEvidence(persisted)}
}
export async function queryDetections(input:{cameraId?:string;eventId?:string;user:any;query:any}){let camera:any;if(input.cameraId){camera=(await supabaseAdmin.from("facility_cameras").select("id,estate_id,metadata").eq("id",input.cameraId).maybeSingle()).data}else{const event=(await supabaseAdmin.from("camera_events").select("camera_id").eq("id",input.eventId).maybeSingle()).data;if(event)camera=(await supabaseAdmin.from("facility_cameras").select("id,estate_id,metadata").eq("id",event.camera_id).maybeSingle()).data}if(!camera||!canAccessCamera(camera,input.user).ok)return{ok:false as const,code:"detection_access_denied"};const limit=Math.min(100,Math.max(1,Number(input.query.limit)||50));let q=supabaseAdmin.from("camera_detections").select("*").eq("camera_id",camera.id).order("observed_at",{ascending:false}).order("id",{ascending:false}).limit(limit+1);if(input.eventId)q=q.eq("event_id",input.eventId);if(text(input.query.start))q=q.gte("observed_at",text(input.query.start));if(text(input.query.end))q=q.lte("observed_at",text(input.query.end));if(text(input.query.type))q=q.eq("detection_type",normalizeDetectionType(input.query.type));if(text(input.query.zoneId))q=q.eq("visual_zone_id",text(input.query.zoneId));if(Number.isFinite(Number(input.query.minimumConfidence)))q=q.gte("confidence",Number(input.query.minimumConfidence));if(text(input.query.cursor)){const raw=Buffer.from(text(input.query.cursor),"base64url").toString("utf8");q=q.lt("observed_at",raw)}const {data,error}=await q;if(error)return{ok:false as const,code:"detection_query_failed"};const rows=data||[];return{ok:true as const,items:rows.slice(0,limit),nextCursor:rows.length>limit?Buffer.from(rows[limit-1].observed_at).toString("base64url"):null}}
export async function cleanupExpiredDetections(now=new Date().toISOString(),limit=500){const {data,error}=await supabaseAdmin.from("camera_detections").delete().is("event_id",null).lte("expires_at",now).limit(Math.min(1000,Math.max(1,limit))).select("id");if(error)throw error;return{deleted:(data||[]).length}}
